# Generated by Django 4.1.5 on 2024-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_vendor_store_contact_store_location_purchase_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
