# Generated by Django 4.1.5 on 2024-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_inventory_storeinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_quantities',
            field=models.TextField(default='{}'),
        ),
    ]
