# Generated by Django 4.1.5 on 2024-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_store_product_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
